sudo: required

language : generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t anycharge/docker-react-app -f dev.Dockerfile .
script:
  - docker run -e CI=true anycharge/docker-react-app npm run test -- --coverage