sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t anycharge/docker-react-app -f dev.Dockerfile .

script:
  - docker run -e CI=true anycharge/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: docker-react-app
  env: Dockerreactapp-env
  bucket_name: elasticbeanstalk-us-west-1-481045552926
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY